### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by ToothPain** [FuccUTimmy/SteamCardBot#1]
I'm using ubuntu 14.04.5 and got this error.

SyntaxError: Unexpected identifier
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/utils.js:3:14)

**Comment by ToothPain** [comment]
nvm fixed
